// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAihcxSqh19_5_Vt7-lCSmDSVQg4zpghyE',
    appId: '1:663339271798:web:208fa8e4fa50c425010157',
    messagingSenderId: '663339271798',
    projectId: 'invtelas',
    authDomain: 'invtelas.firebaseapp.com',
    storageBucket: 'invtelas.firebasestorage.app',
    measurementId: 'G-J02M2PVX1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvCR34-rEtEw6KS6w559CtObO8vVOXPwU',
    appId: '1:663339271798:android:3b3dc112cebf8551010157',
    messagingSenderId: '663339271798',
    projectId: 'invtelas',
    storageBucket: 'invtelas.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAihcxSqh19_5_Vt7-lCSmDSVQg4zpghyE',
    appId: '1:663339271798:web:284cdbf586bf83d3010157',
    messagingSenderId: '663339271798',
    projectId: 'invtelas',
    authDomain: 'invtelas.firebaseapp.com',
    storageBucket: 'invtelas.firebasestorage.app',
    measurementId: 'G-LFXNB9LK27',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmV0-4MnN0Dc3A2lcaUORAeOhongr3AWY',
    appId: '1:663339271798:ios:152278a436f9c905010157',
    messagingSenderId: '663339271798',
    projectId: 'invtelas',
    storageBucket: 'invtelas.firebasestorage.app',
    iosBundleId: 'com.example.invTelas',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmV0-4MnN0Dc3A2lcaUORAeOhongr3AWY',
    appId: '1:663339271798:ios:152278a436f9c905010157',
    messagingSenderId: '663339271798',
    projectId: 'invtelas',
    storageBucket: 'invtelas.firebasestorage.app',
    iosBundleId: 'com.example.invTelas',
  );

}